export const dataSearch = [


    {
        name: 'P2322',
        description: '22asdfghjkl, dfghjk.ayawu ',
        images: [
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image3.jpg')  
        ]
    },
    {
        name: 'Pasd',
        description: '22asdasdadawu ',
        images: [
            require('./image2.jpg'), 
            require('./image3.jpg'),
            require('./image4.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image4.jpg'), 
            require('./image1.jpg'),
            require('./image3.jpg'),
            require('./image2.jpg'),
            require('./image3.jpg')  
        ]
    },

    
]